redirectsOrigin = "config"
plugins = []
headers = []

[env]
VITE_SUPABASE_URL = "https://pblwmavgqdsiwphtetei.supabase.co"
VITE_SUPABASE_ANON_KEY = "sb_publishable_0PAaXNgcj-gt6ZEya-YWKg_CsR1eN0M"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Usuário\\Desktop\\Curso Claude Code-Jhonatan de Souza\\Projetos Agente Forge\\Meus Projetos\\arena-truco-premium\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]